// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6atFlauu6pgWKjOSx38zdOciq-y5wOQs',
    appId: '1:756594253459:web:406f7fd7b36a72e4447766',
    messagingSenderId: '756594253459',
    projectId: 'speaksphere-12558',
    authDomain: 'speaksphere-12558.firebaseapp.com',
    storageBucket: 'speaksphere-12558.appspot.com',
    measurementId: 'G-8JHHYD2WCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG4UmZPh5HfozEpUHcJXRw8tpGT3-6N9M',
    appId: '1:756594253459:android:9cd3797cead952ce447766',
    messagingSenderId: '756594253459',
    projectId: 'speaksphere-12558',
    storageBucket: 'speaksphere-12558.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlpJ86o0BpInAAebRgq905Gebudu2WLDk',
    appId: '1:756594253459:ios:6d45083f2b480ee4447766',
    messagingSenderId: '756594253459',
    projectId: 'speaksphere-12558',
    storageBucket: 'speaksphere-12558.appspot.com',
    iosBundleId: 'com.example.speakSphere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlpJ86o0BpInAAebRgq905Gebudu2WLDk',
    appId: '1:756594253459:ios:73864f9d883970f2447766',
    messagingSenderId: '756594253459',
    projectId: 'speaksphere-12558',
    storageBucket: 'speaksphere-12558.appspot.com',
    iosBundleId: 'com.example.speakSphere.RunnerTests',
  );
}
